language: java
install: true
jdk:
  - oraclejdk8
jobs:
  include:
    - stage: Compile
      script: ./gradlew clean classes testClasses
    - stage: Test
      script: ./gradlew test
    - stage: Build
      script: ./gradlew build sourcesJar javadocJar
    - stage: Publish
      script:
        - echo "Publish here"
